name: Desplegar portafolio en GitHub Pages

on:
  # se ejecuta cuando se hace un cambio en la rama main o se crea un pull request
  push:
    branches: ["main"]

  workflow_dispatch:

# permisos para que el token de GitHub Pages haga el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir un despliegue concurrente, cancelando los anteriores excepto el que está en progreso.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # descarga el código
        uses: actions/checkout@v4
      - name: Setup Node # configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" 
          cache: 'npm'
      - name: Install dependencies
        run: npm ci # Usa 'ci' para instalaciones limpias en CI/CD
      - name: Build # Construye el sitio estático
        run: npm run build # Ejecuta el script 'build' definido en package.json por Astro
      - name: Setup Pages # Configura GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact # Sube el sitio construido como artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube el contenido de la carpeta 'dist' (salida por defecto de Astro build)
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Solo se ejecuta si el 'build' fue exitoso
    steps:
      - name: Deploy to GitHub Pages # Despliega el artefacto subido
        id: deployment
        uses: actions/deploy-pages@v4